# Header
menu:
    主页: /
    归档: /archives
    分类: /categories
    标签: /tags
    关于: /about

# header
avtor: /img/logo.png
# if the value of avtor is false
say: Welcome 

# background_image
# img/01.jpg
# https://source.unsplash.com/collection/954550/1920x1080
background_image:
    enable: false
    #url: https://source.unsplash.com/collection/954550/1920x1080
    #url: https://source.unsplash.com/collection/954550/1920x1080
    #custom Radom img: https://XXX-youname-XXX.github.io/Random-img/
    #customRadom_url: https://blog-background-1251715642.cos.ap-shanghai.myqcloud.com/
    
# show the motto
# otherwise It shows the site description
motto: false

#index-style: pure or cart
index_style: cart

#index_cart_cover
cover: img/cart_cover.jpg

#page
page_name:
    enable: true

#post
#post_comment
comment:
    enable: true

gitalk:
    enable: true
    clientID: '097e5f5792a7f81b5f45' 
    clientSecret: 'e4cc1f53472fcf3893c281eac6e17c19ca1eb490' 
    repo: comments
    owner: DmuMenDuo
    admin: ['DmuMenDuo']
    #must true
    distractionFreeMode: true
    #去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
    
#post_toc
post_toc:
    enable: true
    number: false
    title: 文章目录

#post_excerpt   
excerpt_link: 展开全文

#footer
footer:
    counter: true
#social
social:
    enable: true
    github: https://github.com/DmuMenDuo
    email: mailto:menduo@smail.nju.edu.cn

#copyright  
since: 2017
cotent_author: menduo

#others 
#rss
rss: /atom.xml

#gallery 
#format: natural or square
gallery_format: natural
#one time to load 4 rows or other count(0,1,2,3,4,5,6......)
gallery_limit: 4
#data url
gallery_data: gallery/data.json

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: -1

#when click, emerge heart
love:
    enable: true

#totop
#enable.true to use totop 
totop:
    enable: true


